### ISSUE TITLE
Reproduce the whole app using React

### ISSUE THREAD

**Issue by AWIXOR** [AWIXOR/1337-contributors#24]
@abellaismail7 suggested reproducing the whole app using React so we assigned this issue to him, and he will be working on it.

**Comment by abellaismail7** [comment]
I tried react only and turns out we need to use a loader for yaml this means we need to integrate webpack which is slow just as gatsby.
You guys pick yaml and you have to live with it.
I tried Jekyll and it works fine. but its not easy to setup on iMacs.

**Comment by MasterKym** [comment]
@abellaismail7 Why don't you convert all the `.yml` to `.json` files ? That should be possible and you just use them ?

**Comment by abellaismail7** [comment]
I don't think it's a good idea. since students are more familiar now with Yaml files.

the current implementation I have, takes 5-10 seconds to install all dependencies. but I can't find any loader that loads all Yaml files in a directory in one object.

since I have no experience with Webpack I am going to create my own.
